name: release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we releasing? (format vX.Y.Z)'
        required: true

permissions:
  contents: write

jobs:
    release:
        name: "release"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
              fetch-depth: 0  

          - name: Configure github-actions[bot]
            run: |
              git config user.name 'github-actions[bot]'
              git config user.email 'github-actions[bot]@users.noreply.github.com'

          - name: Get Latest Release
            run: |
              LATEST=$(curl -s "https://github.com/ashnamehrotra/copa-action/releases/latest" | jq -r .tag_name)
              echo "Latest release version: $LATEST"

          - name: Generate and Push Tags
            run: |
              version=${{ github.event.inputs.release_version }}
              major=$(echo $version | cut -d. -f1)
              minor=$(echo $version | cut -d. -f1-2)

              git tag $version
              git tag $minor -f

              latest_minor=$(echo $LATEST | cut -d. -f2)
              current_minor=$(echo $version | cut -d. -f2)

              if [ "$latest_minor" -gt "$current_minor" ]; then
                echo "Release $version is not latest minor version. Not updating major version."
              else
                git tag $major -f
              fi

              git push --set-upstream origin --tags -f
              
          - name: Create GitHub release
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run : |
              gh release create "${{ github.event.inputs.release_version }}" --generate-notes
