name: release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we releasing? (format vX.Y.Z)'
        required: true

permissions:
  contents: write

jobs:
    release:
        name: "release"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
              fetch-depth: 0  

          - name: Configure github-actions[bot]
            run: |
              git config user.name 'github-actions[bot]'
              git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          - name: Create and push tag
            run: |
              git tag -a "${{ github.event.inputs.release_version }}" -m "${{ github.event.inputs.release_version }}"
              git push --set-upstream origin "${{ github.event.inputs.release_version }}"
              
          - name: Create GitHub release
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run : |
              gh release create "${{ github.event.inputs.release_version }}" --generate-notes