name: test-local
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we releasing? (format vX.Y.Z)'
        required: false

permissions:
  contents: write

jobs:
    release:
        name: "test-local"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
              fetch-depth: 0  

          - name: Build image
            id: build
            uses: docker/build-push-action@v5
            with:
                file: Dockerfile
                load: true
                platforms: linux/amd64
                push: false
      
          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@master
            with:
                image-ref: ${{ steps.build.outputs.imageid }} # or full image name with tag
                format: "json"
                output: "report.json"
                ignore-unfixed: true
                vuln-type: os

          - name: Set up docker
            uses: crazy-max/ghaction-setup-docker@v3
            with:
                version: latest
                daemon-config: |
                    {
                        "experimental": true,
                        "features" : {
                            "containerd-snapshotter": true
                        }
                    }

          - name: Run Copa action
            id: copa
            uses: project-copacetic/copa-action@v1.2.1
            with:
                image: ${{ matrix.images }}
                image-report: "report.json"
                patched-tag: "patched"
                timeout: 5m
                custom-socket: ${SOCKET}
                output: out.json