name: test-local
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we releasing? (format vX.Y.Z)'
        required: false

permissions:
  contents: write

jobs:
    release:
        name: "test-local"
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
              fetch-depth: 0 
              
          - name: Set up docker
            uses: crazy-max/ghaction-setup-docker@v3
            with:
                version: latest
                daemon-config: |
                      {
                          "experimental": true,
                          "features" : {
                              "containerd-snapshotter": true
                          }
                      }
  
          - name: Get socket path
            run: |
                url=$(docker context inspect | jq -r .[0].Endpoints.docker.Host)
                socket_path=$(echo "$url" | awk -F// '{print $2}')
                echo "$socket_path"
                echo "SOCKET=$socket_path" >> $GITHUB_ENV

          - name: Create a local image
            run: |
             docker pull nginx:1.21.6
             docker tag nginx:1.21.6 nginx:local

          - name: Install Trivy
            run: |
                echo "Downloading Latest Trivy Version"
                curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . latest

                ./trivy image --ignore-unfixed --vuln-type os -f json -o report.json --docker-host ${SOCKET} nginx:1.21.6         

          - name: Generate Trivy Report
            uses: aquasecurity/trivy-action@d43c1f16c00cfd3978dde6c07f4bbcf9eb6993ca # 0.16.1
            with:
               scan-type: "image"
               format: "json"
               output: "report.json"
               ignore-unfixed: true
               vuln-type: "os"
               image-ref: nginx:local
            
          - name: Run Copa action
            id: copa
            uses: project-copacetic/copa-action@v1.2.1
            with:
                image: "nginx:local"
                image-report: report.json
                patched-tag: "patched"
                timeout: 5m
                custom-socket: ${SOCKET}
